### ISSUE TITLE
Complete the Home Page - Design Similar to Lemon Squad

### ISSUE THREAD

**Issue by RayanImran** [RayanImran/WeInspect4U#1]
I need to complete the home page of my website and would like it to be designed similar to [Lemon Squad](https://lemonsquad.com/). The goal is to have a professional, clean, and visually appealing layout that is highly sellable.

Feel free to use creativity while working on the existing template I have created. You can also use different images and assets if you feel they will enhance the design. The final home page should effectively convey the service and engage users.

Requirements:

- The layout should be clean, professional, and intuitive for users.
- Ensure the design elements (e.g., fonts, colors, buttons, etc.) are consistent and attractive.
- Include high-quality images that align with the theme and enhance the design.
Ensure that the page is responsive and works well across different devices (e.g., desktop, mobile).
- Use modern design practices to make the page visually appealing and functional.
- Feel free to improve upon any existing elements in the current template.
Reference Website:
[Lemon Squad](https://lemonsquad.com/)

Notes:

- You can use stock images or your own images that fit the design.
- The home page should effectively communicate the purpose of the site and convert visitors into customers.
- Include any calls-to-action (CTAs) that would enhance the site's usability and sales potential.

**Comment by RayanImran** [comment]
@Ali90922 jaldi krdai bro deadline is tomorrow for this issue!

**Comment by Ali90922** [comment]
Tmr night right ? Chal career fair kai baad karta hoon
________________________________

**Comment by Ali90922** [comment]
Yeah merged a pull request into main -- it's better than before -- but will continue working on thus
