### ISSUE TITLE
Image not Extending 

### ISSUE THREAD

**Issue by Ali90922** [RayanImran/WeInspect4U#21]
I'm noticing that the images on my website, like the homepage background and the contact form background, aren’t extending fully to the edges of the screen. This leaves some empty space on the sides, which gives the images a boxed or constrained look, instead of the full-width, immersive effect I'm aiming for

Problem exists on the home page and also on the contact us page, also on form.
![Uploading Screenshot 2024-10-15 at 2.20.16 PM.png…]()

**Comment by hassannauman123** [comment]
- This is not a bug, it is meant to be that way. If you see the Tailwind styles, we have specified  "relative". 

Main branch: components/Home/Carousel.jsx
`line 13:  <div className="**relative** w-full h-[700px] overflow-hidden -mt-1">
`

- If you remove "relative", it will extend to the full width of the screen. 
- I think we should let it stay this way, it's a good practice for UX design. Let me know what others think.
