### ISSUE TITLE
Create Frontend Design for Order Form - Similar to Lemon Squad

### ISSUE THREAD

**Issue by RayanImran** [RayanImran/WeInspect4U#3]
Description:
We need to create the frontend for an order form that is similar in style and functionality to Lemon Squad's order form. The focus is on creating a visually appealing and user-friendly form that guides customers through the ordering process. We will handle the backend once the frontend design is completed.

Requirements:

- Design a clean, intuitive order form interface that closely resembles the form on Lemon Squad's website.
- Ensure that the form includes all necessary fields for collecting user information (e.g., name, contact info, service selection, payment details, etc.).
- The form should guide the user step-by-step through the process, making it easy to complete the order.
- Focus on good UX/UI principles, ensuring the form is responsive and works well across all devices (desktop, mobile, tablet).
Include appropriate validation for form inputs (e.g., required fields, correct email format, etc.).
- Feel free to suggest or include improvements over the reference design if you think they would enhance the user experience.
Reference Website:
Lemon Squad Order Form

Notes:

- This task is focused solely on the frontend design; the backend will be implemented later once the frontend is finalized.
- Ensure that the form design is consistent with the overall theme of our website.
Use placeholder data or mock data for testing purposes.

**Comment by hamzam2mhs** [comment]
Done
