### ISSUE TITLE
CORS Policy Blocking API Requests to Car API from Frontend

### ISSUE THREAD

**Issue by hamzam2mhs** [RayanImran/WeInspect4U#6]
![Screenshot 2024-10-10 at 2 40 46 PM](https://github.com/user-attachments/assets/b20750d2-964b-4d18-88d3-a5441c1d0ce5)

#### Description:
When attempting to fetch vehicle makes and models from the Car API (`https://carapi.app/api/makes`), the requests are being blocked by the browser due to **CORS (Cross-Origin Resource Sharing)** policy. The following error is displayed in the console:

#### Steps to Reproduce:
1. Run the frontend by typing npm `npm run dev` on terminal.
2. Try to fetch vehicle makes by making an API call to `https://carapi.app/api/makes`.
3. Observe the CORS error in the browser console.

#### Expected Outcome:
The API call should successfully return vehicle makes from the Car API, allowing the user to select from the dropdown list in the vehicle form.

#### Actual Outcome:
The API call fails due to CORS policy restrictions, and no data is returned. The error message indicates that the API response does not contain the required `Access-Control-Allow-Origin` header, which leads to the request being blocked by the browser.

#### Possible Solutions:
1. Implement a **backend proxy** in our Express server (`server.js`) to handle the API calls. This will bypass the browser's CORS restrictions as the backend will make the request on behalf of the frontend.
2. Use a **CORS proxy service** temporarily to bypass the restriction, though this is not ideal for production.
3. Contact the Car API provider to request CORS support for frontend applications or check if there are any available settings for enabling CORS for their API.

#### Additional Notes:
This issue is critical as it prevents any interaction with the Car API from the frontend, making it impossible to fetch and display vehicle makes and models in the form.

**Comment by RayanImran** [comment]
Issue is fixed now used https://www.carqueryapi.com/api/0.3/?cmd=getMakes
make sure you have npm install jsonp
@hamzam2mhs continue working on the form
